### ISSUE TITLE
Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by JohannesHome** [arabold/serverless-sentry-lib#15]
The sentry lib binds to the old callbacks provided through the [context](https://github.com/arabold/serverless-sentry-lib/blob/479430b9d23127a24fff2c8f54ceeba54851ca80/src/index.js#L315-L317)

These callbacks do not exist in my lambda Environment and they don't seem to be [documented](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html).

Stack trace of the error:
```
TypeError: Cannot read property 'bind' of undefined { error:
   TypeError: Cannot read property 'bind' of undefined
       at /var/task/src/webpack:/node_modules/serverless-sentry-lib/src/index.js:315:1
       ...
```

**Comment by StephanBijzitter** [comment]
Same issue, slightly different message:
```js
			const originalCallbacks = {
				done: context.done.bind(context), // context is undefined
				succeed: context.succeed.bind(context),
				fail: context.fail.bind(context),
				callback: callback,
			};
```
```
2019-06-04T22:57:11.485Z	bf16a167-5120-4089-8212-3feb3615a9ee	TypeError: Cannot read property 'done' of undefined
at Object.master (/var/task/node_modules/serverless-sentry-lib/src/index.js:315:19)
at exports.handler (/var/src/handler.ts:8:23)
at invoke (/var/runtime/node_modules/awslambda/index.js:288:20)
at InvokeManager.start (/var/runtime/node_modules/awslambda/index.js:151:9)
at Object.awslambda.waitForInvoke (/var/runtime/node_modules/awslambda/index.js:499:52)
```
```ts
import * as RavenLambdaWrapper from 'serverless-sentry-lib';
import Raven from 'raven';

export const master = RavenLambdaWrapper.handler(Raven, async (event) => {
    // code redacted, don't think it's important plus it's quite a lot

    return {
        statusCode: 200,
        body: JSON.stringify({
            ...result,
            master: {
                duration
            }
        })
    };
});
```

**Comment by arabold** [comment]
Will be fixed in next update
